### ISSUE TITLE
Python 2 apps fail when setup.py contains Python-2-specific syntax

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-python#52]
See: https://sourcegraph.com/github.com/mailpile/Mailpile/-/builds/8

In this case, there is a Python-2-style `print` statement in the setup.py.

Logs:
```
48286 build #8 task #8[1]: $ srclib config 
48286 build #8 task #8[1]: Traceback (most recent call last): 
48286 build #8 task #8[1]:   File "/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main 
48286 build #8 task #8[1]:     "__main__", mod_spec) 
48286 build #8 task #8[1]:   File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code 
48286 build #8 task #8[1]:     exec(code, run_globals) 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/srclib-python.py", line 34, in <module> 
48286 build #8 task #8[1]:     main() 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/srclib-python.py", line 23, in main 
48286 build #8 task #8[1]:     scan(os.getcwd()) 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/grapher/scan.py", line 109, in scan 
48286 build #8 task #8[1]:     for pkg in find_pip_pkgs(diry): 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/grapher/scan.py", line 51, in find_pip_pkgs 
48286 build #8 task #8[1]:     setup_dict = pydepwrap.setup_info_dir(setup_dir) 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/grapher/pydepwrap.py", line 21, in setup_info_dir 
48286 build #8 task #8[1]:     info, err = pydep.setup_py.setup_info_dir(setup_dir) 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/pydep/setup_py.py", line 32, in setup_info_dir 
48286 build #8 task #8[1]:     return setup_info(setupfile), None 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/lib/python3.5/site-packages/pydep/setup_py.py", line 66, in setup_info 
48286 build #8 task #8[1]:     runpy.run_path(path.basename(setupfile), run_name='__main__') 
48286 build #8 task #8[1]:   File "/usr/local/lib/python3.5/runpy.py", line 238, in run_path 
48286 build #8 task #8[1]:     code, fname = _get_code_from_file(run_name, path_name) 
48286 build #8 task #8[1]:   File "/usr/local/lib/python3.5/runpy.py", line 213, in _get_code_from_file 
48286 build #8 task #8[1]:     code = compile(f.read(), fname, 'exec') 
48286 build #8 task #8[1]:   File "setup.py", line 77 
48286 build #8 task #8[1]:     print "Faild to run 'make clean'. Bailing out." 
48286 build #8 task #8[1]:                                                   ^ 
48286 build #8 task #8[1]: SyntaxError: Missing parentheses in call to 'print' 
48286 build #8 task #8[1]: Traceback (most recent call last): 
48286 build #8 task #8[1]:   File "/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python", line 13, in <module> 
48286 build #8 task #8[1]:     subprocess.run(args, check=True) 
48286 build #8 task #8[1]:   File "/usr/local/lib/python3.5/subprocess.py", line 711, in run 
48286 build #8 task #8[1]:     output=stdout, stderr=stderr) 
48286 build #8 task #8[1]: subprocess.CalledProcessError: Command '['/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.env/bin/python3.5', '-m', 'srclib-python', 'scan']' returned non-zero exit status 1 
48286 build #8 task #8[1]: failed to scan for source units: scanner [/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python scan]: parsing the STDOUT of the scanner failed with: EOF 
48286 build #8 task #8[1]: FAILED: srclib config (failed to scan for source units: scanner [/srclib/toolchains/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python scan]: parsing the STDOUT of the scanner failed with: EOF) 
```

**Comment by beyang** [comment]
This is dependent would be fixed by https://github.com/sourcegraph/srclib-python/issues/41

**Comment by Unknwon** [comment]
Python2 syntax should be fix by #72, but this specific repo fails with `ImportError: No module named pbr.git`.
